"""add product images and video

Revision ID: 16657a472ce0
Revises: 
Create Date: 2026-09-12 11:44:18.841336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16657a472ce0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('video_platform', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('video_platform')
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
